
CREATE DATABASE IF NOT EXISTS BlogDB;

USE BlogDB;

CREATE TABLE IF NOT EXISTS blogs (
id INT NOT NULL AUTO_INCREMENT,
title VARCHAR(45) NOT NULL,
author VARCHAR(45) NOT NULL,
content VARCHAR(250) NOT NULL,
PRIMARY KEY (id),
UNIQUE INDEX id_UNIQUE (id ASC) VISIBLE
) ENGINE = InnoDB;